/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.DAOTicket;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ticket;

/**
 *
 * @author otvfe
 */
public class VisualizaTicket extends javax.swing.JFrame {

    /**
     * Creates new form Visualiza
     */
    public VisualizaTicket() {
        initComponents();
        
        DAOTicket dadosTicket = new DAOTicket();
        ArrayList<Ticket> listaTickets = new ArrayList();
        listaTickets = dadosTicket.selecionarTodosRegistros();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaTicket.getModel();
        for(Ticket ticket : listaTickets)
        {
            Object[] dados = {
                ticket.getAssunto(), 
                ticket.getSetor(),
                ticket.getStatus(),
                ticket.getTipo_ocorr(),
                ticket.getDt_previsao(),
                ticket.getPrioridade(),
                ticket.getSolicitante(),
                ticket.getResponsavel(),
                ticket.getConteudo()};
            modelo.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTicket = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualizar Ticket");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ASSUNTO", "SETOR", "STATUS", "TIPO_OCORR", "DT_PREVISAO", "PRIORIDADE", "SOLICITANTE", "RESPONSAVEL", "CONTEUDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTicket.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTicket);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelaTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTicketMouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar esse registro?");
        if(resposta == 0)
        {
            
            Ticket ticket = new Ticket();
            int linha = tabelaTicket.getSelectedRow();
            ticket.setId(Integer.parseInt(tabelaTicket.getValueAt(linha, 0).toString()));
            ticket.setAssunto(tabelaTicket.getValueAt(linha, 1).toString());
            ticket.setSetor(tabelaTicket.getValueAt(linha, 2).toString());
            ticket.setStatus(tabelaTicket.getValueAt(linha, 3).toString());
            ticket.setTipo_ocorr(tabelaTicket.getValueAt(linha, 4).toString());
            ticket.setDt_previsao(tabelaTicket.getValueAt(linha, 5).toString());
            ticket.setPrioridade(tabelaTicket.getValueAt(linha, 6).toString());
            ticket.setSolicitante(tabelaTicket.getValueAt(linha, 7).toString());
            ticket.setResponsavel(tabelaTicket.getValueAt(linha, 8).toString());
            ticket.setConteudo(tabelaTicket.getValueAt(linha, 9).toString());
            
            
            
            new AlterarTicket(ticket).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tabelaTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizaTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTicket;
    // End of variables declaration//GEN-END:variables
}
